### ISSUE TITLE
Piping output differs from input and fails?

### ISSUE THREAD

**Issue by arichiardi** [types/npm-ramda#175] opened 2017-05-10 22:29 UTC
Hello!

I got this:

![2017-05-10-152040_572x118_scrot](https://cloud.githubusercontent.com/assets/1724788/25924015/5da120d2-3595-11e7-9c98-c5e506a530c6.png)

And error:

```
13   return R.pipe(
     ~~~~~~~~~~~~~~
14     R.evolve(aggregateSanitation),
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
15     R.props(["domain", "name", "id"])
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16   )(aggregate);
   ~~~~~~~~~~~~~~~

src/impl/file-persistence.ts(13,3): error TS2322: Type '{}[]' is not assignable to type 'string[]'.
  Type '{}' is not assignable to type 'string'.
```

I solved with casting, but I was wondering whether there is a better way to fix it?

Thanks a lot for typing `ramda`!

**Comment by arichiardi** [comment] 2017-05-10 22:44
This also solves:

```
interface WasteOfTimeFn { (obj: any): string[]; };

function aggregate(aggregate: AggregateIdentifier): string[] {
  return R.pipe(
    R.evolve(aggregateSanitation),
    <WasteOfTimeFn>R.props(["domain", "name", "id"])
  )(aggregate);
}
```

**Comment by tycho01** [comment] 2017-05-11 07:40
Yeah, it's our top issue, minimum repro being `R.pipe(R.identity)` (reason: presence of generics it does not yet have the info to resolve, instead yielding `{}`). A [fix](https://github.com/Microsoft/TypeScript/issues/9949#issuecomment-271926278) would pretty much require TypeScript to better prioritize this. Feel free to upvote / voice your support over there, for what it's worth.

**Comment by tycho01** [comment] 2017-08-15 04:02
This issue is still a thing, but I'll close as dupe of #86.

**Closed by tycho01** 2017-08-15 04:02 UTC
