### ISSUE TITLE
Requires declaration

### ISSUE THREAD

**Issue by dakom** [types/npm-ramda#184] opened 2017-07-13 15:53 UTC
Using the R typings requires adding a `declare const R;` at the top of the file, or importing R

Is this expected behavior? I don't encounter that with other packages which I need typings for but only import at runtime via cdn (e.g. PIXI)

**Comment by tycho01** [comment] 2017-07-13 16:19
To my knowledge import syntax (as opposed to just require) is idiomatic in TypeScript, yeah.

Looks like they're doing [the following](https://github.com/pixijs/pixi-typescript/blob/v4.x/pixi.js.d.ts#L3454-L3461):
```ts
declare namespace PIXI {
  ...
}

declare namespace pixi {
  export const gl: typeof PIXI.glCore;
}
 
//tslint:disable-next-line:no-single-declare-module
declare module "pixi.js" {
  export = PIXI;
}
```

We're doing this:
```ts
declare var R: R.Static;
declare namespace R {
  ...
}
export = R;
```

I'm not sure exactly how you're using these typings or TS if not using imports -- I'm trying to figure out whether the behavior you're looking for is caused by their `pixi` namespace or by their module declaration -- probably the latter.

It's hard for me to verify my guess as I don't know how to reproduce your use-case. Would it be possible for you to try adding such a module declaration in your local ramda typings copy to verify what might fix this for you? I apologize I'm not too knowledgeable in this area.

**Comment by ikatyang** [comment] 2017-07-14 07:29
It seems the [`export as namespace R`](http://www.typescriptlang.org/docs/handbook/modules.html#umd-modules) is missing in this repo, which marks the definition as UMD compatible.

**Comment by tycho01** [comment] 2017-07-14 07:43
Thanks, I tried adding that now. I'm guessing this means the functions would need to be declared/exported from the top level as well though?

**Comment by ikatyang** [comment] 2017-07-14 07:51
`export as namespace R` means that `module.exports` is named `R` in UMD, all you have to do is just adding an `export as namespace R`, since `export = R` is already done all things.  :)

**Comment by tycho01** [comment] 2017-07-14 07:52
Great! If @dakom can confirm this as working I guess we're good then. :)

**Comment by dakom** [comment] 2017-07-14 08:09
hmm with latest commit I'm still getting `'R' refers to a UMD global'R' refers to a UMD global`

**Comment by ikatyang** [comment] 2017-07-14 08:10
@dakom can you share some steps to reproduce?

**Comment by dakom** [comment] 2017-07-14 08:20
From this work-in-progress repo: [sodium-typescript-playground](https://github.com/dakom/sodium-typescript-playground/tree/f978228f3ca3ddec948056c4f121246031657f24)

If you comment out the [declare const R](https://github.com/dakom/sodium-typescript-playground/blob/f978228f3ca3ddec948056c4f121246031657f24/src/lib/funcs/PrimitiveFuncs.ts#L1), then you get the error

(to run the repo, after `npm install` it's `npm run dev` to spin up a local dev webpack server etc.)

**Comment by dakom** [comment] 2017-07-14 08:27
This looks relevant - https://github.com/Microsoft/TypeScript/issues/3180#issuecomment-283007750

**Comment by dakom** [comment] 2017-07-14 08:41
OK, seems it's more of a general typescript issue: https://github.com/Microsoft/TypeScript/issues/10178

**Comment by ikatyang** [comment] 2017-07-14 08:42
UMD is considered no `import/export`s.
module is considered `import/export`s.

In this case, R is considered global variable, so that you have to handle it yourself.

(tsconfig.json)

```json5
{
  "include": [
    "../src/**/*.ts",
    "../types/*" // <----
  ],
}
```

(./types/ramda.d.ts)

```ts
import * as _R from 'ramda';
declare global {
    const R: typeof _R; // <-- set R as global variable
}
```

**Comment by dakom** [comment] 2017-07-14 08:59
Yep - your solution fixed it, thanks :-D

**Comment by dakom** [comment] 2017-07-14 09:08
fwiw, VSCode is acting strange with it... compiles and completes fine, but VSCode still hilights the usage with an error/warning :\

**Comment by tycho01** [comment] 2017-07-14 09:10
might VSCode not be using the same TS version? That's one possibility, though I think I've otherwise seen discrepancies as well... pretty weird.

**Comment by ikatyang** [comment] 2017-07-14 09:14
@dakom you have to put your `tsconfig.json` in the root folder, otherwise it'll just use the default settings. Or setup some config for that in vscode? I don't know if there is the option.

**Comment by dakom** [comment] 2017-07-14 09:18
ugh... now I tried it in a different project and got more errors again. I think I'm going to forget about trying to use it as a global, adding a `declare` or `import` at the top of each file isn't the end of the world

**Comment by tycho01** [comment] 2017-07-14 09:22
@dakom yeah, I do wish we had global imports as well.
I was doing Angular, and ng-cli did something for adding globals, though that'd also still just error within the actual files...
If you do find a solution I'd be pretty interested as well. I agree the boilerplate is annoying.

**Comment by tycho01** [comment] 2017-08-15 03:41
Closing as not having ways to solve this makes it sorta non-actionable; if we do find a way then let's retry.

**Closed by tycho01** 2017-08-15 03:41 UTC
